FROM ubuntu:bionic

ENV ROOT_PATH="/opt/my_service"

ADD fixed_requirements.txt requirements.txt
RUN echo installing \
    && apt-get update -qq \
    && apt-get install -y \
        python3 \
        python3-pip \
    && pip3 install --update pip \
    && pip3 install -r fixed_requirements.txt \
    && mkdir -p ${ROOT_PATH}

ADD model.tar.gz ${ROOT_PATH}/model
COPY . ${ROOT_PATH}
WORKDIR ${ROOT_PATH}

EXPOSE 5000
ENTRYPOINT ["python3", "appMain.py"]
