apiVersion: v1
kind: Service
metadata:
  name: fallback-webapp
  labels:
    app: fallback-webapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: fallback-webapp
