apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-webapp
  labels:
    app: main-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-webapp
  template:
    metadata:
      labels:
        app: main-webapp
    spec:
      containers:
      - name: main-webapp
        image: antone/mainimage:latest
        env:
          - name: MODEL_PATH
            value: "/opt/my_service/model/model/"
        ports:
          - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
