class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_download_options = {"ssl-no-revoke" => true}
  config.vm.provider "virtualbox" do |vbox|
    vbox.memory = 6096
    vbox.cpus = 2
  end
  config.vm.network "private_network", type: "dhcp"
  config.vm.hostname = "minikube"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
